### ISSUE TITLE
about graceful-shutdown

### ISSUE THREAD

**Issue by gq-tang** [gin-gonic/examples#11]
https://github.com/gin-gonic/examples/blob/2a6477130d67ce3369c23f3677c52dba6abe61a0/graceful-shutdown/graceful-shutdown/server.go#L52

Must I add this line of code here? Does it have any effect?

**Comment by BenWUKFast** [comment]
Just ran into this. I removed that. In theory we should get the error message for context timeout in:

`if err := srv.Shutdown(ctx); err != nil {`

Since that waits for ctx.Done() or returns early. The example could do with some fleshing out.

**Comment by gq-tang** [comment]
When < -ctx.done () is added, the service shuts down normally ahead of time, but the program still waits for the timeout to expire.
< -ctx.done () already has timeout processing in srv.Shutdown (ctx), so I wonder if I can leave this processing out.

**Comment by appleboy** [comment]
@gq-tang Yes. I will remove the `<-ctx.done()`
