### ISSUE TITLE
File Binding Not Working!

### ISSUE THREAD

**Issue by fcu-d0515211** [gin-gonic/examples#14]
```go
type UpdateUserOperatorReq struct {
	File     *multipart.FileHeader `form:"file"`
	UID      *string                        `form:"uid" json:"uid"`
}

...

req := &UpdateUserOperatorReq{}
if err := c.ShouldBind(req); err != nil {
	c.JSON(status, "")
	return
}
logger(req.File)
// <nil>
```

I follow the example, but still getting nil. Please help fix this bug

**Comment by thinkerou** [comment]
please see https://github.com/gin-gonic/examples/tree/master/file-binding
and you need to use gin `master` branch.

**Comment by fcu-d0515211** [comment]
I Update my gin `go get -u github.com/gin-gonic/gin` 
Also cant use.

**Comment by fcu-d0515211** [comment]
Fixed!
Follow [#1673](https://github.com/gin-gonic/gin/issues/1673#issuecomment-482023570) Guide
