### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by hugohabicht01** [gin-gonic/examples#36]
I just tried to get started with gin and I am struggling a bit with unit testing my sample app. Would it be possible to add a example with tests so that I can see how to properly test gin applications?

**Comment by appleboy** [comment]
See https://gin-gonic.com/docs/testing/

**Comment by hugohabicht01** [comment]
That isnt really explaining anything at all. I think everybody will be able to test a "ping pong route" by himself. I am more looking for some testing of a little rest api and not just one route with always the same output....

**Comment by appleboy** [comment]
You can see the more example in https://github.com/appleboy/gofight
