### ISSUE TITLE
More than one service

### ISSUE THREAD

**Issue by FeruzOripov** [gin-gonic/examples#4]
Can I implement more than one service and one api or should api be one for each service? I mean can gin api be one for 4 or 5 services ?

**Comment by thinkerou** [comment]
what's mean? can you post some example code? thanks!

**Comment by FeruzOripov** [comment]
Oh, sorry it was related to grpc example. I wanted to ask can I implement one api for more than one grpc services.

**Comment by thinkerou** [comment]
@FeruzOripov sure, quick think:
grpc: `grpc_a` and `grpc_b`
api: `/rest/n/:name`, `name` is `a` => call `grpc_a`, `b` => call `grpc_b`
right?
