### ISSUE TITLE
There is some example how to use gqlgen + dataloaden + gin?

### ISSUE THREAD

**Issue by mirusky** [gin-gonic/examples#47]
I found [this](https://github.com/99designs/gqlgen/blob/master/docs/content/recipes/gin.md) recipe in gqlgen repo, but I don't find a way in how to use GraphQL Dataload with Gin

**Comment by appleboy** [comment]
I will take it.

**Comment by mirusky** [comment]
@appleboy someone exaplaned to me how to setup a minimal working example in [gqlgen repo](https://github.com/99designs/gqlgen/issues/1439) also is related to [dataloader repo](https://github.com/vektah/dataloaden/issues/56).

I will apreciate if some minimal example code be done here. But since someone helped me to find an answer I will close this issue.
