### ISSUE TITLE
graceful-shutdown(in https://github.com/gin-gonic/examples/blob/master/graceful-shutdown/graceful-shutdown/server.go)

### ISSUE THREAD

**Issue by Jarnpher553** [gin-gonic/examples#6]
select {
case <-ctx.Done():
	log.Println("timeout of 5 seconds.")
}

why is not under?

select {
case <-ctx.Done():
	log.Println("timeout of 5 seconds.")
default:
}

**Comment by thinkerou** [comment]
if you need `default`, please do it, thanks!
