### ISSUE TITLE
How can i generate assets.go???

### ISSUE THREAD

**Issue by vantrung8794** [gin-gonic/examples#60]
![image](https://user-images.githubusercontent.com/56285732/126495999-74cacc5f-c7d4-4cc6-b2bd-4785814a74c5.png)

How can I do right now? I could not use command go-assets-builder html -o assets.go
And the result is always zsh: command not found: go-assets-builder
Please help me...

**Comment by appleboy** [comment]
You can try the following example using embed in Go 1.16

https://github.com/gin-gonic/examples/tree/master/assets-in-binary/example02

**Comment by mumingv** [comment]
@vantrung8794 maybe you can install the command go-assets-builder as follows:
```
go get github.com/jessevdk/go-assets-builder
go install github.com/jessevdk/go-assets-builder@latest
```
