### ISSUE TITLE
The following error exists in the http2 package

### ISSUE THREAD

**Issue by iwanzhang** [gin-gonic/examples#76]
open ./testdata/server.pem: no such file or directory

**Comment by thinkerou** [comment]
not reproduce

<img width="770" alt="image" src="https://user-images.githubusercontent.com/4488261/180968064-7027c765-3a80-4a7d-8546-a4b3f49204c3.png">

**Comment by thinkerou** [comment]
```
cd http2
go run main.go
```
it's ok!
